package georgi.gaydarov.gos.compiler.translator;

public enum RawStatementType {
DECLARATION,
DIRECT_ASSIGNMENT,
DIRECT_OPERATION,
OPERATION_ASSIGNMENT,
COMPLEX_OPERATION_ASSIGNMENT,
FUNCTION_CALL;
}
